
export const PROTOCOL_VERSION = 14;
export const ARTNET_PACKET_ID = 'Art-Net'
export const ARTNET_PORT = 6454
export const DEFAULT_POLL_INTERVALL = 5000
export const DEVICE_DEATH_TIMEOUT_MS = 10000

export enum OP_CODE {
    OP_POLL = 0x2000,
    OP_POLL_REPLY = 0x2100,
    OP_DIAG_DATA = 0x2300,
    OP_DMX = 0x5000
}

export enum ARTNET_MESSAGE {
    POLL_REPLY = 'POLL_REPLY',
    POLL = 'POLL',
    DEVICE_STATUS_UPDATE = 'DEVICE_STATUS_UPDATE',
    NEW_DEVICE_REGISTERED = 'NEW_DEVICE_REGISTERED'
}
